name: Fetch scoped access token
description: Fetch a scoped access token
author: FriendsOfShopware
branding:
  color: "blue"
  icon: "download"

inputs:
  id:
    required: true

outputs:
  token:
    description: "Token"

runs:
  using: 'node20'
  main: 'dist/main/main.js'
  post: 'dist/post/main.js'
